"use client";

import VideoCarousel from "@/components/VideoCarousel";
import { useLanguage } from "@/i18n/LanguageContext";
import { strings } from "@/i18n/strings";

export default function HeroCarousel() {
  const { lang } = useLanguage();
  const t = strings[lang];

  // The carousel prefers optimized outputs generated by scripts/transcode-videos.sh
  // which creates two MP4 files per original: `<name>.av1.mp4` and `<name>.h264.mp4`.
  // We keep a `src` fallback to current repo files so the app runs before conversion.
  const items = [
    {
      id: "medImport",
      // Fallback to existing asset until the script is run
      src: "/videos/med_import_demo.mov",
      sources: [
        { src: "/videos/med_import_demo.av1.mp4", type: "video/mp4; codecs=\"av01\"" },
        { src: "/videos/med_import_demo.h264.mp4", type: "video/mp4; codecs=\"avc1.640028\"" },
      ],
    },
    {
      id: "arRecognition",
      src: "/videos/AR_recognition.mp4",
      sources: [
        { src: "/videos/AR_recognition.av1.mp4", type: "video/mp4; codecs=\"av01\"" },
        { src: "/videos/AR_recognition.h264.mp4", type: "video/mp4; codecs=\"avc1.640028\"" },
      ],
    },
    {
      id: "arTalk",
      src: "/videos/AR_talk_llm.mp4",
      sources: [
        { src: "/videos/AR_talk_llm.av1.mp4", type: "video/mp4; codecs=\"av01\"" },
        { src: "/videos/AR_talk_llm.h264.mp4", type: "video/mp4; codecs=\"avc1.640028\"" },
      ],
    },
    {
      id: "bindGuard",
      src: "/videos/bind_guard.MP4",
      sources: [
        { src: "/videos/bind_guard.av1.mp4", type: "video/mp4; codecs=\"av01\"" },
        { src: "/videos/bind_guard.h264.mp4", type: "video/mp4; codecs=\"avc1.640028\"" },
      ],
    },
    {
      id: "bindElderly",
      src: "/videos/bind_elderly.MP4",
      sources: [
        { src: "/videos/bind_elderly.av1.mp4", type: "video/mp4; codecs=\"av01\"" },
        { src: "/videos/bind_elderly.h264.mp4", type: "video/mp4; codecs=\"avc1.640028\"" },
      ],
    },
  ].map((it) => ({
    title: it.id,
    caption: t.videoCaptions[it.id] || "",
    src: it.src,
    sources: it.sources,
  }));

  return <VideoCarousel items={items} />;
}
